{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <unit.test_pytest.TestClass object at 0x0000029988E4CEF0>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\nunit\\test_pytest.py:27: AssertionError"}, "attachments": [{"name": "stdout", "source": "b0f263cf-6bf4-4e2a-a751-eedd076b0cc1-attachment.txt", "type": "text/plain"}], "start": 1582965708017, "stop": 1582965708018, "uuid": "968e6bcd-908b-4ae9-a3fc-932f0ea2c596", "historyId": "f29c6df3a2c6e467cf125441fc92b055", "testCaseId": "89fea8c6fc1c84d5ebed1bc186c1df83", "fullName": "unit.test_pytest.TestClass#test_two", "labels": [{"name": "parentSuite", "value": "unit"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "LAPTOP-GLFLRPL6"}, {"name": "thread", "value": "20968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_pytest"}]}