{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(3)", "trace": "def test_answer():\n>       assert inc(3) == 5\nE       assert 4 == 5\nE        +  where 4 = inc(3)\n\nunit\\test_pytest.py:6: AssertionError"}, "attachments": [{"name": "stdout", "source": "f2f9a9c7-4e66-417c-898e-0342d5706ce3-attachment.txt", "type": "text/plain"}], "start": 1582965707986, "stop": 1582965707986, "uuid": "dcc3d791-98bd-4900-ab28-ba883e7b4b2e", "historyId": "d4078a36c7b82cdf5cebd2653a5fe2e7", "testCaseId": "bf4ea236332438f0d8cd452e21501480", "fullName": "unit.test_pytest#test_answer", "labels": [{"name": "parentSuite", "value": "unit"}, {"name": "suite", "value": "test_pytest"}, {"name": "host", "value": "LAPTOP-GLFLRPL6"}, {"name": "thread", "value": "20968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "unit.test_pytest"}]}